/**
 * Centralized English copy for the enterprise area (FR-051).
 * Components must reference copy via `copy.*` — never hard-code user-visible strings.
 */
export const copy = {
  brand: { name: 'Contoso Survey Hub', shortName: 'Survey Hub' },
  demoUser: { displayName: 'Alex Rivera', roleLabel: 'Survey Operations Lead' },
  nav: {
    home: 'Home',
    surveys: 'Surveys',
    responses: 'Responses',
    participants: 'Participants',
    help: 'Help',
    favorites: 'Favorites',
    favoritesEmpty: 'No favorites yet. Star records, views, or pages to pin them here.',
    toggleNav: 'Toggle navigation',
    collapse: 'Collapse navigation',
    expand: 'Expand navigation',
  },
  header: {
    searchPlaceholder: 'Search surveys, responses, people\u2026',
    searchTrigger: 'Search',
    searchShortcut: 'Ctrl+K',
    notifications: 'Notifications',
    profile: 'Account menu',
  },
  profile: {
    settings: 'Settings',
    appearance: 'Appearance',
    accessibility: 'Accessibility',
    shortcuts: 'Keyboard shortcuts',
    help: 'Help & tour',
    reset: 'Reset demo data',
    resetConfirmTitle: 'Reset demo data?',
    resetConfirmBody: 'This clears your preferences, saved views, favorites, drafts, and read state, then returns you to a fresh first-run experience. This cannot be undone.',
    resetTypedWord: 'RESET',
    signOutHint: 'Demo session (single user)',
  },
  settings: {
    title: 'Settings',
    appearanceLabel: 'Appearance',
    light: 'Light',
    dark: 'Dark',
    system: 'Use system setting',
    accessibilityLabel: 'Accessibility mode',
    accessibilityBody: 'Always-visible focus, minimized motion, larger targets, maximum contrast.',
    densityLabel: 'Table density',
    comfortable: 'Comfortable',
    compact: 'Compact',
    saved: 'Settings saved',
  },
  states: {
    loading: 'Loading\u2026',
    retry: 'Try again',
    backHome: 'Back to home',
    emptyTitle: 'Nothing here yet',
    notFoundTitle: 'This page could not be found',
    notFoundBody: 'The link may be outdated, or the demo content was reset.',
  },
  dashboard: {
    welcomePrefix: 'Welcome back',
    quickActions: 'Quick actions',
    quickActionsEmpty: 'No quick actions configured for this demo.',
    recentActivity: 'Recent activity',
    recentEmpty: 'Things you visit will show up here.',
    viewAll: 'View all',
    favorites: 'Favorites',
    favoritesEmpty: 'Star a survey, response, participant, or saved view and it will appear here.',
  },
  collections: {
    search: 'Search this collection',
    filter: 'Filter',
    clearFilters: 'Clear filters',
    personalize: 'Personalize',
    density: 'Density',
    views: 'Views',
    saveView: 'Save view',
    saveViewAs: 'Save as new view',
    viewName: 'View name',
    export: 'Export',
    exportCsv: 'Export CSV (current page)',
    exportAllCsv: 'Export CSV (all matching)',
    exportJson: 'Export JSON (all matching)',
    bulkBar: '{count} selected',
    selectAll: 'Select all rows',
    clearSelection: 'Clear selection',
    archive: 'Archive',
    delete: 'Delete',
    confirmBulkTitle: 'Archive {count} surveys?',
    confirmBulkBody: 'This runs as a simulated demo action \u2014 no data is permanently changed.',
    rowsPerPage: 'Rows per page',
    resultsSummary: '{start}\u2013{end} of {total}',
    noRows: 'No records match your current filters.',
    noRowsHint: 'Try adjusting or clearing the filters to see more.',
    columnPicker: 'Columns',
    exportSuccess: 'Export ready \u2014 check your downloads.',
    exportError: 'Export failed. Please try again.',
    archiveSuccess: 'Archived {count} survey(s) (simulated).',
    archiveError: 'Bulk action failed. Please try again.',
  },
  task: {
    launchTitle: 'Launch a survey',
    next: 'Continue',
    back: 'Back',
    submit: 'Launch survey',
    submitting: 'Launching\u2026',
    draftSaved: 'Draft saved just now',
    resumeTitle: 'Resume your draft?',
    resumeBody: 'You have an in-progress draft from {time}. Continue where you left off?',
    resume: 'Resume draft',
    discard: 'Discard draft',
    successTitle: 'Survey launched!',
    successBody: 'Your survey is now active. Responses will appear in the Responses area shortly.',
    stepInvalid: 'Please fix the highlighted fields before continuing.',
  },
  notifications: {
    title: 'Notifications',
    markAllRead: 'Mark all as read',
    clearAll: 'Clear all',
    emptyTitle: 'You\u2019re all caught up',
    emptyBody: 'New activity (responses, launches, alerts) will appear here.',
    markRead: 'Mark as read',
    clear: 'Clear',
    all: 'All',
    unread: 'Unread',
    justNow: 'Just now',
  },
  search: {
    title: 'Global search',
    emptyTitle: 'No matches for \u201c{query}\u201d',
    emptyBody: 'Check the spelling, or browse Surveys / Responses / Participants instead.',
    suggestion: 'Did you mean \u201c{suggestion}\u201d?',
    groupPages: 'Pages',
    groupRecords: 'Records',
    groupViews: 'Saved views',
    groupActions: 'Actions',
    openHint: '\u2191\u2193 to navigate \u00b7 Enter to open \u00b7 Esc to close',
  },
  help: {
    title: 'Help & shortcuts',
    tour: 'Guided tour',
    replayTour: 'Replay the guided tour',
    helpIndex: 'Contextual help',
    shortcuts: 'Keyboard shortcuts',
  },
  shortcutMap: {
    openSearch: 'Open global search',
    openNotifications: 'Open notifications',
    toggleDark: 'Toggle dark mode',
    toggleA11y: 'Toggle accessibility mode',
    openHelp: 'Open help',
    focusCommand: 'Focus command bar',
    goHome: 'Go to home',
  },
  toast: {
    saved: 'Saved',
    resetDone: 'Demo data reset \u2014 starting fresh.',
  },
  dialog: { cancel: 'Cancel' },
  dateTime: {
    locale: 'en-US',
    short: { year: 'numeric', month: 'short', day: 'numeric' },
  },
} as const;

/** Formats an ISO timestamp for display in the current copy locale. */
export function formatDateTime(iso: string): string {
  const date = new Date(iso);
  if (Number.isNaN(date.getTime())) return iso;
  return date.toLocaleString(copy.dateTime.locale, {
    month: 'short',
    day: 'numeric',
    hour: 'numeric',
    minute: '2-digit',
  });
}

/** Interpolates {placeholders} in a template string with values. */
export function interpolate(template: string, values: Record<string, string | number>): string {
  return template.replace(/\{(\w+)\}/g, (match, key) => (key in values ? String(values[key]) : match));
}
